cluster.name: cluster-es
network.host: 0.0.0.0
path.data: /data/elasticsearch/data
path.logs: /data/elasticsearch/logs
http.cors.enabled: true
http.cors.allow-origin: "*" 

xpack.ml.enabled: false
xpack.monitoring.enabled: false
xpack.security.enabled: false
xpack.watcher.enabled: false

node.name: ${POD_NAME:${HOSTNAME}}
bootstrap.memory_lock: ${MEMORY_LOCK:true}
discovery.zen.ping.unicast.hosts: ${DIS_HOSTS:${HOSTNAME}}
discovery.zen.minimum_master_nodes: ${DIS_NUMBER:1}

node.master: ${NODE_MASTER:true}
node.ingest: ${NODE_INGEST:true}
