version: '2.2'
services:
  es-0:
    image: harbor.bbotte.com/devops/es6:0.6
    container_name: es-0
    environment:
      - POD_NAME=es-0
      - DIS_HOSTS=es-0,es-1,es-2
      - MEMORY_LOCK=true
      - DIS_NUMBER=2
      - XPACKMONITORING=true
      - XPACKCOLLECTION=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /tmp/1:/data/elasticsearch
    ports:
      - 9200:9200
    networks:
      - elastic
  es-1:
    image: harbor.bbotte.com/devops/es6:0.6
    container_name: es-1
    environment:
      - POD_NAME=es-1
      - DIS_HOSTS=es-0,es-1,es-2
      - MEMORY_LOCK=true
      - DIS_NUMBER=2
      - XPACKMONITORING=true
      - XPACKCOLLECTION=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /tmp/2:/data/elasticsearch
    networks:
      - elastic
  es-2:
    image: harbor.bbotte.com/devops/es6:0.6
    container_name: es-2
    environment:
      - POD_NAME=es-2
      - DIS_HOSTS=es-0,es-1,es-2
      - MEMORY_LOCK=true
      - DIS_NUMBER=2
      - XPACKMONITORING=true
      - XPACKCOLLECTION=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /tmp/3:/data/elasticsearch
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
