server:
  port: 9151
spring:
  ##################服务名称############################
  application:
    name: ${EUREKA_APPLICATION_NAME:eureka}
  profiles:
    active: dev
##################Eureka 注册配置############################
eureka:
  environment: ${ENVIRONMENT:dev}
  instance:
    hostname: ${MY_POD_NAME:eureka}.${MY_IN_SERVICE_NAME:localhost}
    appname: ${MY_IN_SERVICE_NAME:spring.application.name}
    prefer-ip-address: false
    instance-id: ${MY_POD_NAME:${spring.application.name}}:${MY_IN_SERVICE_NAME:localhost}:${EUREKA_SERVER_PORT:9151}
    #服务刷新时间配置，每隔这个时间会主动心跳一次 默认 30秒
    lease-renewal-interval-in-seconds: 30
    ## 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: ${EUREKA_URL_LIST:http://${MY_POD_NAME:${HOSTNAME}}.${MY_IN_SERVICE_NAME:}:${EUREKA_SERVER_PORT:9151}/eureka/}
    register-with-eureka: ${BOOL_REGISTER:true}
    fetch-registry: ${BOOL_FETCH:true}
    healthcheck:
      enable: true
    registry-fetch-interval-seconds: 10
  server:
    ## 启用主动失效，并且每次主动失效检测间隔为3s
    eviction-interval-timer-in-ms: 2000
    enable-self-preservation: ${SELF_PRESERVATION:true}

##################logback 配置##############################
logback:
  logFilePath: /opt/log/dev
  logFileName: ${spring.application.name}
